### ISSUE TITLE
browser option

### ISSUE THREAD

**Issue by pavan3999** [mensch272/novelsave#54]
Browser options not working when trying in termux, how to use it?

**Comment by mensch272** [comment]
novelsave does not support browser options in mobile.

It is using `browser_cooke3` library to retrieve cookies from the browser, the library only supports desktop.

**Comment by pavan3999** [comment]
okay, any alternative for webnovel.com login?

**Comment by mensch272** [comment]
You'll to use novelsave on desktop with the browser option. Im not aware any other alternatives for mobile.

WebToEpub chrome extension might work, but that is still desktop.

**Comment by mensch272** [comment]
I'll be closing this issue now.

Please create another issue if you have any more questions.
