### ISSUE TITLE
Unable to deploy

### ISSUE THREAD

**Issue by damare01** [mensch272/novelsave#67]
**Describe the bug**
Can't deploy the bot because there is no app.json file

**Comment by mensch272** [comment]
I dont think `app.json` is required to run the web app. My current deployment does not use it either.

**Comment by damare01** [comment]
> I dont think `app.json` is required to run the web app. My current deployment does not use it either.

@mensch272 I tried deploying it on heroku, it failed because there is no app.json file. What is the command to run discord bot?

**Comment by damare01** [comment]
Is it npm start? And is the build command "pip install -r requirements.txt"?

**Comment by mensch272** [comment]
This is the command to run the bot.

https://github.com/mensch272/novelsave/blob/48b1789ea412378f00f6291cf4cda9f525baa8f2/Procfile#L1

Heroku automatically installs dependencies by using `pip install -r requirements.txt` when using the python build pack.

**Comment by damare01** [comment]
> This is the command to run the bot.
> 
> https://github.com/mensch272/novelsave/blob/48b1789ea412378f00f6291cf4cda9f525baa8f2/Procfile#L1
> 
> Heroku automatically installs dependencies by using `pip install -r requirements.txt` when using the python build pack. Could you describe your process in more detail so I may provide better help.

I will just deploy it on railway, thank you!
