### ISSUE TITLE
Web Deployment?

### ISSUE THREAD

**Issue by damare01** [mensch272/novelsave#69]
Can this be deployed as a website?

**Comment by damare01** [comment]
> It can, but it does not have a web client implemented. I had plans for it, but with changes in real life, I haven't been able to devote much time to this.

how about forking this [repo](https://github.com/littledivy/wattpad-downloader) and add new sources on it?

**Comment by mensch272** [comment]
Frankly, that would be a lot of work. And from a preliminary look, the architecture of the project also doesn't seem to support multiple sources.
