### ISSUE TITLE
Asset recognition error when a novel uses same asset more than once

### ISSUE THREAD

**Issue by damare01** [mensch272/novelsave#70]
**Describe the bug**
`❗ (sqlite3.IntegrityError) UNIQUE constraint failed: assets.novel_id, assets.url
[SQL: INSERT INTO assets (name, url, path, type_id, novel_id) VALUES (?, ?, ?, ?, ?)]
[parameters: ('Belator', 'https://user-pic.webnovel.com/userheadimg/4300020728-10/100.jpg?uut=1549988455000', None, 1, 1)]
(Background on this error at: https://sqlalche.me/e/14/gkpj)`

**Comment by mensch272** [comment]
Would you mind providing the novel in question?

**Comment by damare01** [comment]
I was downloading this [novel](https://boxnovel.com/novel/rebirth-of-the-godly-prodigal/), I tried downloadig it now the bot wroked perfectly fine.
