### ISSUE TITLE
ERROR: Package 'novelsave' requires a different Python: 3.8.10 not in '<4.0,>=3. 9'

### ISSUE THREAD

**Issue by idMysteries** [mensch272/novelsave#73]
After version 0.8.1, python 3.8 is no longer supported?

https://pypi.org/project/novelsave/0.8.3/
Requires: Python >=3.9, <4.0

**Comment by mensch272** [comment]
The normal command line would work, This is a bug. Though the discord server won't run properly in 3.8.

**Comment by mensch272** [comment]
Fixed
